version: '3'

services:

  redis:
    image: redis
    ports:
      - '6379'

  db:
    image: postgres:14.7-alpine
    environment:
      - POSTGRES_DB=kyc
      - POSTGRES_PASSWORD=123qwe
      - PGDATA=/var/lib/postgresql/data/pg_data
    volumes:
      - pg_data:/var/lib/postgresql/data/pg_data  
    ports:
      - '5432'  
    healthcheck:  
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    tty: true
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py ccsu
      && python manage.py runserver 0.0.0.0:8003"
    ports:
      - '8003:8003'
    env_file:
      - ./admin/.env.docker
    depends_on:
      db:
        condition: service_healthy

  api:
    build: ./api
    tty: true
    command: >
      bash -c "uvicorn main:app --reload --port 8002 --host 0.0.0.0"
    ports:
      - '8002:8002'
    env_file:
      - ./api/.env.docker
    depends_on:
      db:
        condition: service_healthy

  worker:
    build: ./api
    tty: true
    env_file:
      - ./api/.env.docker
    command: >
      bash -c "celery --app=src.app.worker worker --concurrency=1 --loglevel=DEBUG"
    depends_on:
      - redis
      - api


volumes:
  pg_data:
