# Generated by Django 5.0.1 on 2024-01-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя файла')),
                ('size', models.IntegerField(verbose_name='Размер файла')),
                ('content_type', models.CharField(max_length=30, verbose_name='Тип файла')),
                ('filename', models.CharField(max_length=30, unique=True, verbose_name='Имя файла на диске')),
                ('is_public', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('status', models.CharField(choices=[('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='under_review', max_length=12, verbose_name='Статус файла')),
                ('upload_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время загрузки файла')),
                ('change_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения статуса')),
            ],
            options={
                'db_table': 'file',
            },
        ),
    ]
